### ISSUE TITLE
Please include a more detailed guide. 

### ISSUE THREAD

**Issue by Herculade** [fredldotme/Box64AndWine#7]
I'm an Ubuntu touch noob, installed today. I have been eyeing off this repo for a while. 

I Just dont know how to use it. I cloned the repo and ran the build.sh and it said that it was missing the INSTALL path so I exported one. 
Then it was missing make - i installed it through apt. 
Then it was missing g++ - i installed it again through apt. 
Then it was missing a cmake requirements file in pe-parse and I found one on the pe-parse git page.
I then read a closed issue of someone asking how do you install it and you said you don't even need apt - don't touch it. Much confuse please assist.

**Comment by fredldotme** [comment]
The first thing you should do is check the right docs. Like every other Ubuntu Touch app it is built using `clickable`, ie one command that doesn't need more explanation: https://clickable-ut.dev/en/latest/

The docs are linked at the UBports docs site as well, so I'll close this.
